### ISSUE TITLE
Suggestion for different envato image on landing page

### ISSUE THREAD

**Issue by NathanDennis** [EddieHubCommunity/EddieHubCommunity.github.io#10]
https://elements.envato.com/teamwork-UP8MCL7
or
https://elements.envato.com/technology-concept-8FW5ASH

**Comment by gagangaur** [comment]
I would suggest going with the first one because that's what the motive of the community

**Comment by eddiejaoude** [comment]
thanks @NathanDennis 👍 and @gagangaur 👍

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
