### ISSUE TITLE
Bug - Community name and hero photo displaying something else

### ISSUE THREAD

**Issue by frankiefab100** [EddieHubCommunity/EddieHubCommunity.github.io#116]
When sharing the website link, it shows Steve's face and Amadine's name instead of the hero photo and our community name.

![Screenshot](https://user-images.githubusercontent.com/624760/99060240-a4cb2c00-2597-11eb-952d-7dcf3ff3e62a.png)

**Comment by eddiejaoude** [comment]
Please add a description with an example, similar to the original Discussion https://github.com/EddieJaoudeCommunity/support/discussions/425

**Comment by frankiefab100** [comment]
@eddiejaoude I hope I got it right?🙂

**Comment by eddiejaoude** [comment]
Look better, can you add the image too 

You can use this

```html
<img width="498" alt="Screenshot 2020-11-13 at 10 01 49" src="https://user-images.githubusercontent.com/624760/99060240-a4cb2c00-2597-11eb-952d-7dcf3ff3e62a.png">
```

**Comment by jai-dewani** [comment]
Does this looks okay? 
![image](https://user-images.githubusercontent.com/33520257/106476376-03d07b00-64cd-11eb-96cb-55973e34d9ae.png)
