### ISSUE TITLE
Meta data for website preview is incorrect

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#124]
Currently looks like

<img width="489" alt="Screenshot 2021-01-28 at 20 49 15" src="https://user-images.githubusercontent.com/624760/106197198-526ad600-61aa-11eb-971b-4b14b58b9656.png">

**Comment by Vyvy-vi** [comment]
linked to first-timers `discussion`- [support#425](https://github.com/EddieJaoudeCommunity/support/discussions/425)

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by jai-dewani** [comment]
I wanna take this. 
Which website was this tested on?

**Comment by eddiejaoude** [comment]
Thanks @jai-dewani 👍 

This repo and GitHub Pages https://eddiehubcommunity.github.io

**Comment by jai-dewani** [comment]
Does this look okay? 

![image](https://user-images.githubusercontent.com/33520257/106476462-19de3b80-64cd-11eb-9867-9f478d2b76d5.png)

**Comment by eddiejaoude** [comment]
Looks great, thank you 👍
