### ISSUE TITLE
Add our community video to our website

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#125]
https://www.youtube.com/watch?v=z-FKAC0I_VQ&feature=youtu.be

Ideas for the future
- get the community members in the video to say a few words
-

**Comment by Prathamkrishna** [comment]
I'm not sure where you want to put the video exactly but I did find a spot, at the home page instead of the black background and the photo.


![Screenshot (275)](https://user-images.githubusercontent.com/34184758/106219672-e450fe00-61ff-11eb-9066-9ba7aa69ff35.png)

**Comment by eddiejaoude** [comment]
@Prathamkrishna I think you are right, instead of the photo makes sense 👍

**Comment by Prathamkrishna** [comment]
I think i'd like to take up on this issue

**Comment by eddiejaoude** [comment]
Sure 👍 I have assigned it to you 🤓

**Comment by Prathamkrishna** [comment]
Made a pull request :)

**Comment by jai-dewani** [comment]
Since the community video has been added, this issue can be closed or any further work is required on this issue?

**Comment by eddiejaoude** [comment]
Thanks @jai-dewani , you are right, lets close. Any future work can have a new issue
