### ISSUE TITLE
READ.me file

### ISSUE THREAD

**Issue by Prathamkrishna** [EddieHubCommunity/EddieHubCommunity.github.io#128]
i'm not sure but i think the read.me file has a screenshot of the home page of the website. Now that there is an update on the home page, is there a need to change the screenshot.

**Comment by eddiejaoude** [comment]
I think it would make sense to update it 👍

**Comment by patel-himanshu** [comment]
@eddiejaoude, can I take up this issue?

**Comment by Vyvy-vi** [comment]
Go on-! : )
