### ISSUE TITLE
Missing a mod on the website

### ISSUE THREAD

**Issue by AhmadsAxioms** [EddieHubCommunity/EddieHubCommunity.github.io#130]
Nicholas, one of the moderators of the discord community  is missing in the community website.
https://eddiejaoudecommunity.github.io/

**Comment by eddiejaoude** [comment]
Thanks for raising @ApolloDev0

**Comment by ApolloDev0** [comment]
your welcome :)

**Comment by mdPial** [comment]
I would like to work on that 😃️

**Comment by rohank2502** [comment]
Hey As this is good first issue I will like to help in this !! please let me know how to approach

**Comment by vikasganiga05** [comment]
> Nicholas, one of the moderators of the discord community is missing in the community website.
> https://eddiejaoudecommunity.github.io/

The website URL is changed to https://eddiehubcommunity.github.io/

**Comment by vikasganiga05** [comment]
Hi, I like to work on this issue.

**Comment by eddiejaoude** [comment]
Thanks all, looks like there are still mods missing. Please go ahead and add missing mods 👍

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
