### ISSUE TITLE
Missing Another Mod on the website!

### ISSUE THREAD

**Issue by ApolloDev0** [EddieHubCommunity/EddieHubCommunity.github.io#131]
Allan Regush, one of the discord moderators is missing on the community website.
https://eddiejaoudecommunity.github.io/

**Comment by eddiejaoude** [comment]
Thanks for raising @ApolloDev0

**Comment by mdPial** [comment]
I would like to work on that 😃️

**Comment by jai-dewani** [comment]
I guess we will need information like `description`, `website`, `imageSrc`, `GitHub username` and `badges` to add him to `data.js`

**Comment by eddiejaoude** [comment]
yep 👍 this is their GitHub profile to find out more @AllanRegush
