### ISSUE TITLE
Automated tests are failing because of recent change in website URL 

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/EddieHubCommunity.github.io#135]
Pull Request Automated tests seem to be failing because they are still trying to reach https://eddiejaoudecommunity.github.io/ which is now https://eddiehubcommunity.github.io/.   

![image](https://user-images.githubusercontent.com/33520257/106502110-f4abf600-64e9-11eb-85b1-0e0dce90cb96.png)
This should be easily fixed by updating the URL stored in [.github/workflows/lighthouse-check.yml](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/.github/workflows/lighthouse-check.yml)

https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/7c3a07b8287738f67b60af2e73916a101cedf4e1/.github/workflows/lighthouse-check.yml#L20

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by Nitesh-thapliyal** [comment]
PR is comming🙌
