### ISSUE TITLE
Links to GitHub Organization and Repositories need update

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/EddieHubCommunity.github.io#139]
All the GitHub links stored in [EddieHubCommunity.github.io/src/data.js](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/src/data.js) are obsolete and will now have to be updated as the community name got changed recently. 

Links to all the projects 
https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/94de45ad97fc6469a3c5536aff7aace12d9f4263/src/data.js#L65-L74

Including the link to the organization at the end
https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/94de45ad97fc6469a3c5536aff7aace12d9f4263/src/data.js#L226-L229

And if anything else that I might be missing

**Comment by deephunt3r** [comment]
The github icon which is referring to the link https://github.com/EddieJaoudeCommunity  in the website was broken.Please update the link in the website https://eddiehubcommunity.github.io/
