### ISSUE TITLE
linkedin website preview not working

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#146]
```html
    <meta property="og:url" content="https://eddiehubcommunity.github.io">
    <meta property="og:type" content="website">
    <meta property="og:title" content="EddieHub Community">
    <meta property="og:description" content="We believe Open Source is for everyone, yes you!">
    <meta property="og:image" content="https://eddiehubcommunity.github.io/img/hero.svg">
```

https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en

<img width="519" alt="Screenshot 2021-02-06 at 10 16 09" src="https://user-images.githubusercontent.com/624760/107115416-7bebc780-6864-11eb-8f5e-6fa0f0bd93fa.png">

**Comment by jai-dewani** [comment]
I checked on both Twitter and linkedin, the text seems to be working fine. It's the image linking that needs to be worked on 
Twitter 
![image](https://user-images.githubusercontent.com/33520257/110017535-557a5880-7d4c-11eb-99ec-76ca392ef2a9.png)

LinkedIn
![image](https://user-images.githubusercontent.com/33520257/110017577-5dd29380-7d4c-11eb-9d85-872b65206fab.png)

**Comment by jai-dewani** [comment]
Seems like the `og:image` does not support SVG format so we might have to store a png format of hero.svg image currently used with meta tags  

Reference - https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images

**Comment by eddiejaoude** [comment]
oh good spot, thank you @jai-dewani 👍

**Comment by eddiejaoude** [comment]
I have updated it to a `png` image, hopefully now it is better? https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/main/public/index.html

**Comment by jai-dewani** [comment]
It's working!!! 
Time to close another issue 😌 

### Twitter
![image](https://user-images.githubusercontent.com/33520257/110939548-99c4b480-835b-11eb-93ac-62c71f9c3450.png)
### LinkedIn
![image](https://user-images.githubusercontent.com/33520257/110939577-a517e000-835b-11eb-92fe-12aee269e9c6.png)

**Comment by eddiejaoude** [comment]
Thanks @jai-dewani
