### ISSUE TITLE
Update "Our Moderators" section 

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/EddieHubCommunity.github.io#148]
I see @Vyvy-vi is now moderator. Maybe it's time to put @Vyvy-vi in the red spot?

![mod](https://user-images.githubusercontent.com/73097560/109149804-0445f400-77a3-11eb-92f5-d25c5f3cd667.png)

**Comment by eddiejaoude** [comment]
Yep we have a few mods missing from the website 😢

**Comment by Vyvy-vi** [comment]
Allan Regush and Nicholas need to be added first 🤓

**Comment by jai-dewani** [comment]
I think Allan has been added, next are Nicholas and Vyvy-vi 🥳

**Comment by vinzvinci** [comment]
> I think Allan has been added, next are Nicholas and Vyvy-vi 🥳
> Also, I think the same point has been raised by #130 though that issue was pointing to the absence of Nicholas from the website

Cool, thank you.

**Comment by pvcodes** [comment]
Hi, give the required info for Nicholas and Vyvy-vi for the moderator section.

**Comment by pvcodes** [comment]
> Hi, give the required info for Nicholas and Vyvy-vi for the moderator section.

Hi, @eddiejaoude , please provide the content

**Comment by eddiejaoude** [comment]
@pvcodes  You can get the information from @nhcarrigan  GitHub profile page http://github.com/nhcarrigan

**Comment by pvcodes** [comment]
@eddiejaoude That's good, can you please assign me this issue

**Comment by Vyvy-vi** [comment]
More info can be found on Nick's site-  https://www.nhcarrigan.com/

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
