### ISSUE TITLE
Reduce the size of images used in website

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/EddieHubCommunity.github.io#155]
### The Lighthouse test of the website is around 50 for mobile and about 75 in desktop, mobile side definitely need some improvement 
![image](https://user-images.githubusercontent.com/33520257/111602495-653c7700-87f9-11eb-9513-bd3c1af6f42e.png)

### The main cause in mobile seems to be that the website loads about 4.5MB of data out of which 4MB seems to be just images which aren't event used in their native resolution in the website, The amount of data sounds a lot less but is a lot since this can cause the website the feel slow in cellular network during bad reception 
![image](https://user-images.githubusercontent.com/33520257/111602749-adf43000-87f9-11eb-8790-46d7fc543249.png)

**Comment by SamDev98** [comment]
Will using imgbot be enough? Or a good start? (In case we don't already have one here)

**Comment by jai-dewani** [comment]
Yes, imgbot is a good start but the problem with that is most of the heavy images aren't in this repo locally which is a must for utilising imgbot efficiently.

I guess we can start with that task first and then move forward with imgbot.

What's your view on this @EddieHubCommunity/coreteam?

**Comment by BOLT04** [comment]
@jai-dewani thank you for opening this issue 👍. From #98 I guess some metrics have worsened.

I agree on improving and reading that list

**Comment by eddiejaoude** [comment]
Thanks all 👍 , maybe the images should be moved into the repo - I dot like binaries in the repo but they won't change too often to be an issue

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
