### ISSUE TITLE
Remove EddieBotMap from the website 

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/EddieHubCommunity.github.io#156]
### We still have a project on the website pointing to a link that doesn't exists 
This can be replaced with some other project, say........[gh-action-community](https://github.com/EddieHubCommunity/gh-action-community)  

![image](https://user-images.githubusercontent.com/33520257/111603704-a1240c00-87fa-11eb-8120-b7703ee6ff02.png)

**Comment by pvcodes** [comment]
Hi, I would love to care of this. Should I start?   If yes, please provide me the [https://github.com/EddieHubCommunity/gh-action-community](gh-action-community)'s image and content of the description

**Comment by pvcodes** [comment]
> Hi, I would love to care of this. Should I start? If yes, please provide me the [https://github.com/EddieHubCommunity/gh-action-community](gh-action-community)'s image and content of the description

Also, correct me if my comment seems to mean, this stuff is new to me.

**Comment by jai-dewani** [comment]
Description: GitHub Action for the Community, from welcoming first timers to badges (Just for the time being, maybe we will have another issue to update this if needed) 

Image: For now take a screenshot of the repository as an image, something like this 
![image](https://user-images.githubusercontent.com/33520257/111795731-79fa3700-88ed-11eb-88ef-c54545a45b9f.png)

### PS: In Light mode, not dark. Light mode provides better contrast specially when the image is going to be very small section of the screen

**Comment by pvcodes** [comment]
So should I proceed. And to be on the safe side. Steps would be:
1. Fork the repo
2. Make a new branch
3. Edit the code
4. Apply for PR

**Comment by jai-dewani** [comment]
Yep, those are the right steps I belive 👍

**Comment by pvcodes** [comment]
Where should I save the image. Maybe here [https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/tree/main/public/img](url)

**Comment by pvcodes** [comment]
![Screenshot from 2021-03-19 20-41-09](https://user-images.githubusercontent.com/54075838/111803731-576c1c00-88f5-11eb-87df-6afa73ae917f.png)

**Comment by pvcodes** [comment]
> Where should I save the image. Maybe here [https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/tree/main/public/img](url)

I google that stuff, that's fine

**Comment by pvcodes** [comment]
Hi @jai-dewani, It's done have a look. And if it is fine give me a thumbs up for the next step i.e., PR

![Screenshot from 2021-03-19 21-14-04](https://user-images.githubusercontent.com/54075838/111806610-2b9e6580-88f8-11eb-97ed-501c18391e36.png)
`
  {
    name: 'GitHub Action Community',
    imageSrc: 'https://user-images.githubusercontent.com/54075838/111803731-576c1c00-88f5-11eb-87df-6afa73ae917f.png',
    description: 'GitHub Action for the Community, from welcoming first timers to badges.',
    link: 'https://github.com/EddieHubCommunity/gh-action-community',
    techList: [
      techIconsData.javascript,
    ]
  },
`

**Comment by pvcodes** [comment]
@jai-dewani hi, I'm waiting!

**Comment by eddiejaoude** [comment]
Hi @pvcodes , apologies for the slow reply, please be patient with the community, we do this in addition to our day jobs and family.

Did you mean to close your PR #157 ?

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
