### ISSUE TITLE
Add new img

### ISSUE THREAD

**Issue by rohank2502** [EddieHubCommunity/EddieHubCommunity.github.io#158]
Will  like to add img collaboration first code section below that white box in website

**Comment by rohank2502** [comment]
![Clean Work Place LinkedIn Banner](https://user-images.githubusercontent.com/76584243/111971513-6edc1c80-8b22-11eb-83df-277a0a8f4fd8.png)

**Comment by pvcodes** [comment]
@rohank2502 
![Screenshot from 2021-03-23 19-14-33](https://user-images.githubusercontent.com/54075838/112156249-12552c00-8c0c-11eb-8f17-02f1b9f6e2b1.png)

**Comment by pvcodes** [comment]
> @rohank2502
> ![Screenshot from 2021-03-23 19-14-33](https://user-images.githubusercontent.com/54075838/112156249-12552c00-8c0c-11eb-8f17-02f1b9f6e2b1.png)

Have a Look

**Comment by rohank2502** [comment]
> 
> 
> > @rohank2502
> > ![Screenshot from 2021-03-23 19-14-33](https://user-images.githubusercontent.com/54075838/112156249-12552c00-8c0c-11eb-8f17-02f1b9f6e2b1.png)
> 
> Have a Look
I think it should have size of that white box but first we need approval from @eddiejaoude

**Comment by pvcodes** [comment]
> > > @rohank2502
> > > ![Screenshot from 2021-03-23 19-14-33](https://user-images.githubusercontent.com/54075838/112156249-12552c00-8c0c-11eb-8f17-02f1b9f6e2b1.png)
> > 
> > 
> > Have a Look
> > I think it should have size of that white box but first we need approval from @eddiejaoude

Certainly

**Comment by Vyvy-vi** [comment]
Maybe open a PR? That way, maintainers can have a bit of back and forth, before Eddie sees it. That way we can rule out any issues.

Moreover, thanks for the art. You could maybe add this in https://github.com/EddieHubCommunity/Branding ?

In the current site's context, I'm not sure about the colour scheme.

Also, is this an image element or an frontend element?

**Comment by rohank2502** [comment]
> o, is this an image element or an frontend element?

This is png element

**Comment by eddiejaoude** [comment]
I agree with @Vyvy-vi , can this be added to the `community` section in the `Branding` repo
