### ISSUE TITLE
Add Navbar and extra white space between sections

### ISSUE THREAD

**Issue by BrendaMichellle** [EddieHubCommunity/EddieHubCommunity.github.io#160]
I was thinking it would be a good idea to add a navbar to the website so it is easier to use and navigate. 
Visitors would be able to click and go to the section they are looking for. 

Also if we add some extra white space between the sections it could help to clearly define each section. 

I could take up the issue or is someone else is interested. 🙂

**Comment by DevCassie** [comment]
I agree with the navbar with Brenda 👍 . A navigation bar would make the website easier to use and navigate to. 

Not too sure about more whitespace for the different sections. For me, it's obvious that the sections are apart. 
I do however suggest some more whitespace here:
![image](https://user-images.githubusercontent.com/19227530/113769905-cd5bea00-9721-11eb-857e-8a5764f07f17.png)

**Comment by kaiwalyakoparkar** [comment]
@BrendaMichellle That is a good idea. Do you have any design in mind :question:

**Comment by DevCassie** [comment]
> @BrendaMichellle That is a good idea. Do you have any design in mind ❓

Wasn't someone slowly re-designing the website? I'm not sure if that's still going on. But perhaps that could be implemented with more whitespace for the sections?

**Comment by eddiejaoude** [comment]
@SaraJaoude is now helping out with EddieHub, so we will take the website into our "low code" platform we are using - this way Sara can keep it up to date and events, calls etc 

Please can still give ideas and feedback on the design 🤓 . But I will close this for now

**Comment by kaiwalyakoparkar** [comment]
@eddiejaoude No worries. :smiley:

**Comment by schmelto** [comment]
> @SaraJaoude is now helping out with EddieHub, so we will take the website into our "low code" platform we are using - this way Sara can keep it up to date and events, calls etc 

Yes low code 🚀 @eddiejaoude maybe you can make a video about this cause low code is a topic I would be really interested in 🤔

**Comment by kaiwalyakoparkar** [comment]
@schmelto True. I didn't even know what this means :sweat_smile:

**Comment by eddiejaoude** [comment]
Sure a video is a great idea 👍  it is actually on my list

<img width="376" alt="Screenshot 2021-05-09 at 08 33 59" src="https://user-images.githubusercontent.com/624760/117563966-56f43400-b0a1-11eb-9b8f-5872887fe3af.png">
