### ISSUE TITLE
Update Favicon on EddieHub Community Website

### ISSUE THREAD

**Issue by Evavic44** [EddieHubCommunity/EddieHubCommunity.github.io#165]
`EddieHubCommunity` website still uses the old logo and I think it needs to be updated
<br/>
![update-eddiehub-favicon](https://user-images.githubusercontent.com/62628408/116830965-acfa4080-aba4-11eb-833f-5dd56ac32f3b.png)
 to the new logo 👉🏾 <img src="https://user-images.githubusercontent.com/62628408/116830606-5e987200-aba3-11eb-8835-6ce305996571.png" width="50px" height="50px">

**Comment by yashsehgal** [comment]
Hey, Is this issue still open to grab? I would like to work on this one.

**Comment by schmelto** [comment]
> Hey, Is this issue still open to grab? I would like to work on this one.

I would say yes. Don't see any pr for this so I suggest you can give it a go 🚀

**Comment by yashsehgal** [comment]
> > Hey, Is this issue still open to grab? I would like to work on this one.
> 
> I would say yes. Don't see any pr for this so I suggest you can give it a go 🚀

Alright @schmelto, I will add the new logo as soon as I get free 👍🏽

**Comment by schmelto** [comment]
> Where can the new EddieHub logo be gotten from? @schmelto
there is a branding repo for that https://github.com/EddieHubCommunity/Branding

**Comment by yashsehgal** [comment]
My bad, I was not able to contribute. By the way, Nice work @Evavic44

**Comment by schmelto** [comment]
@yashsehgal maybe you can take a look at the EddieBot (https://github.com/EddieHubCommunity/EddieBotUI/blob/develop/public/eddie-jaoude.png) in here the old Logo is visible. But ifk if this will be intended to change. But probably you can raising an issue for this one there and open a PR 😃

**Comment by Evavic44** [comment]
> My bad, I was not able to contribute. By the way, Nice work @Evavic44

Thank you man.

**Comment by schmelto** [comment]
Think this is done now
![image](https://user-images.githubusercontent.com/30869493/118172593-d92b8200-b42c-11eb-912b-fbfb8741ae0d.png)
