### ISSUE TITLE
Low Performance on LightHouse Benchmark

### ISSUE THREAD

**Issue by AllanRegush** [EddieHubCommunity/EddieHubCommunity.github.io#167]
Desktop:
Score of 41
![desktop_eddiehub](https://user-images.githubusercontent.com/17693494/117232376-3ba5d200-adde-11eb-8a96-0df1556c8789.png)
Mobile:
Score of 58
![mobile_eddiehub](https://user-images.githubusercontent.com/17693494/117232381-3ea0c280-adde-11eb-89f4-c6a4f0744c20.png)

**Comment by eddiejaoude** [comment]
Is this still relevant? Now we are using low code solution Kartra, I am not sure how much control we have with improving its score

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-06-19 at 2 53 00 PM](https://user-images.githubusercontent.com/62864373/122637772-1232d280-d10e-11eb-811c-38889d1934b6.png)
The current metrics are relatively okay

**Comment by BOLT04** [comment]
@eddiejaoude do you know if there is a way in Kartra to modify code? Or perhaps content or settings to improve performance, etc. If not I don't think we can do much about LightHouse's metrics.

**Comment by eddiejaoude** [comment]
Sorry for my slow reply @BOLT04 - I am behind in my GitHub notifications

Yes we can modify the code, but I am not sure if we break any low-code functionality - we can try it

**Comment by xkrishguptaa** [comment]
The performance is much better from Katra and the source code is there now, so I think it might be a better idea to open issues with specific improvements.
<img width="959" alt="image" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/135469703/f167cea9-87b9-4e54-9357-ae988f9ae003">

Therefore closing this
