### ISSUE TITLE
Update link to home-page in EDDIEHUB text logo

### ISSUE THREAD

**Issue by verma-kunal** [EddieHubCommunity/EddieHubCommunity.github.io#169]
When on the Newsletter or the Blogs page, the **`EDDIEHUB`** text logo is not clickable.
Adding the link to the `Homepage` i.e `https://www.eddiehub.org/` in that would make it much convenient for navigation!!

Logo Image:
![Screenshot 2021-05-14 at 12 00 35 AM](https://user-images.githubusercontent.com/72245772/118170167-6aa7ed80-b447-11eb-93b2-4a972c6e2998.png)

**Comment by SaraJaoude** [comment]
Thank you for this issue.  It has now been resolved.
