### ISSUE TITLE
some minor tweaks for eddiehub.org

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/EddieHubCommunity.github.io#170]
* don't autoplay the first video
* paddings and margins in modarator view are little bit off seeing in this screenshot
![image](https://user-images.githubusercontent.com/30869493/118172316-80f48000-b42c-11eb-83b0-948f39988ba0.png)
* personally I would preffere if the icons would be green like done 
![image](https://user-images.githubusercontent.com/30869493/118172397-9b2e5e00-b42c-11eb-803b-5dea8c022432.png)
* maybe bring back the community projects section with Eddiebot v2.0 🚀

**Comment by SaraJaoude** [comment]
> don't autoplay the first video

Thanks for the feedback, this has been done.

> paddings and margins in modarator view are little bit off seeing in this screenshot

I have checked on Chrome and Safari and these seem fine.  Would you mind sharing what browser and version you saw this on as a new issue? 

> personally I would preffere if the icons would be green like done

Thanks - I have used the website's green. 

> maybe bring back the community projects section with Eddiebot v2.0

Great idea. I have raised this as a new issue: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/174

**Comment by schmelto** [comment]
> I have checked on Chrome and Safari and these seem fine. Would you mind sharing what browser and version you saw this on as a new issue?

I use Microsoft Edge Version 90.0.818.62 (Official build) (64-bit) with chromium base

**Comment by eddiejaoude** [comment]
Thank you @schmelto

**Comment by adityaraute** [comment]
Is there any PR regarding this?

**Comment by SaraJaoude** [comment]
> Website built using Kartra a low code platform. This repo is only used to for Issues to track ideas / improvements / suggestions / bugs etc.

As mentioned in the first line of the README quoted above, no PRs can be made as this is a low code platform managed by Eddie Jaoude and I.

**Comment by adityaraute** [comment]
Ahh alright. But then are those suggestions implementable? (Not sure if that's a word to be honest)

**Comment by SaraJaoude** [comment]
We are looking into whether these changes can be implemented by the low code platform.

**Comment by adityaraute** [comment]
Oh Kartra is a paid service offering developed business websites as I see it. Would be hard to get the CSS change refined. Have yall gotten in touch with the Support team there?

**Comment by eddiejaoude** [comment]
CSS changes can be made but often breaks the page in other ways.

I will close this issue as part of it is done. Individual issues can be created for each item going forwards.
