### ISSUE TITLE
Some Feedback on eddiehub.org@v2

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/EddieHubCommunity.github.io#171]
The new site looks really great! I have some feedback about the site, which might help us in improving the site-

## No Mention of Livestreams, Reviews etc.
Maybe there can be a mention of community livestreams that are Eddie holds on the youtube channel.

## Metadata from meta tags
Many of the meta tags on the site are currently empty, but if we fill them in, the embeds generated by twitter/discord would look fantastic.
![Screenshot of meta tags](https://user-images.githubusercontent.com/62864373/118242380-e68f4d80-b4ba-11eb-848d-fc7449d3d1f7.png)

I'll suggest, that maybe we fill in these somewhat like this-
```html
<meta name="title" content="EddieHub">
<meta name="description" content="
Open Source community aimed at encouraging and promoting communication, best practices and technical expertise in an inclusive and welcoming environment">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#f74700">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta property="og:title" content="EddieHub">
<meta property="og:description" content="
Open Source community aimed at encouraging and promoting communication, best practices and technical expertise in an inclusive and welcoming environment">
<meta property="og:image" content="https://kartrausers.s3.amazonaws.com/eddiejaoude/19257292_608fc94c60f27_9.png">
```
#### The current embed-
![old embed that just has title](https://user-images.githubusercontent.com/62864373/118243775-6d90f580-b4bc-11eb-8c8b-e792a3d6e6cd.png)
#### Embed after meta tags -
![neat embed due to of meta tags](https://user-images.githubusercontent.com/62864373/118246276-615a6780-b4bf-11eb-9130-79ad4325a15d.png)

## About the stars and the testimonials-
- I'm not sure if the stars on the testimonials make much difference since the text in the testimonials speaks for itself.
- Maybe the button at the button of the testimonials section can be tweaked a bit to have text like "read more testimonials"

## Footer github link-
- Maybe the github icon in the footer can link to http://github.eddiehub.org/ instead of the github link to ensure that the link doesn't break in the future.

## Issues with the faq-
- There's a small issue with the FAQs. The animation breaks after 3-4 down button press and the text turns gray-ish and un-readable.
![Broken Animation in FAQs](https://media.discordapp.net/attachments/699608417928740944/842484826921893949/Screenshot_2021-05-14_at_12.50.54_AM.png)

**Comment by SaraJaoude** [comment]
> No mention of Livestreams, Reviews, etc. 

Thanks for this.  I have raised this as a new issue: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/175

> Metadata from meta tags

Thanks for the suggestions, I have done this. 

> About the stars and the testimonials-

I have checked with Eddie and he likes the visual representation of the stars.  

I am looking to see if the button can be amended to reflect the text you suggest.

> Footer github link-

Thanks, done.

> Issues with the faq-

We have tried this a few times and have not managed to break it.  Could you please let us know what browser and version you are using and raise this as an issue?

**Comment by Vyvy-vi** [comment]
> We have tried this a few times and have not managed to break it. Could you please let us know what browser and version you are using and raise this as an issue?

I'm using `Brave Version 1.22.71 with Chromium: 89.0.4389.114 (Official Build) (x86_64)`
I'll open a new issue for this :+1:

**Comment by SaraJaoude** [comment]
Thanks! 

Also on: 

> About the stars and testimonials-

Have managed to change the button as you suggested.
