### ISSUE TITLE
Minor changes for new website

### ISSUE THREAD

**Issue by namangupta1399** [EddieHubCommunity/EddieHubCommunity.github.io#173]
![image](https://user-images.githubusercontent.com/53571307/118272727-aa6ee380-b4e0-11eb-8e5f-6ffff3ee74c6.png)
- Change the color of favicons to white
- Add a **go to top** button

**Comment by Liri-s29** [comment]
@namangupta1399 Can I work on this issue?

**Comment by namangupta1399** [comment]
@Liri-s29 , I don't think that the code for new website is public right now. We should wait I guess 😅

**Comment by Liri-s29** [comment]
Yeah @namangupta1399, I was also looking for the repo.

**Comment by eddiejaoude** [comment]
@Liri-s29 @namangupta1399 the website is being done in a low-code solution, so unfortunately the source code will be contained within that platform

**Comment by SaraJaoude** [comment]
> Change the color of favicons to white

Thanks for raising this, it will be dealt with as part of the issue: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/175

> Add a go to top button

Thanks for the suggestion.  We will add this when the page gets longer.
