### ISSUE TITLE
Overflow issue on testamonials

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/EddieHubCommunity.github.io#176]
![Screenshot_20210520_141351.jpg](https://user-images.githubusercontent.com/30869493/118976775-ae35b680-b975-11eb-917e-357e166cab37.jpg)

Mobile view

**Comment by eddiejaoude** [comment]
Thank you 👍 , this could be a tricky one to fix, but we can try 🤓

**Comment by SaraJaoude** [comment]
The website is created with a low code platform and only Eddie and myself can make amendments. It does not appear that this issue can be easily fixed. I am closing this issue as this only affects a small number of users who have smaller mobile screens.
