### ISSUE TITLE
Shout-Out to folks organising the Public Speaking Sessions

### ISSUE THREAD

**Issue by verma-kunal** [EddieHubCommunity/EddieHubCommunity.github.io#177]
It would be great if we give shout-outs in the **Public Speaking section** to folks who are helping/organising these sessions every week on **RadioEddie**

Some names are as below:
- @kaiwalyakoparkar for hosting the call
- @verma-kunal for co-hosting
- @starlightknown and @Vyvy-vi for being present and also moderating the call

**Comment by SaraJaoude** [comment]
This has been done and will be reflected on the website shortly.

**Comment by schmelto** [comment]
@SaraJaoude rocks the eddiehub website 💪🏼🚀

**Comment by kaiwalyakoparkar** [comment]
> @SaraJaoude rocks the eddiehub website 💪🏼

That's true :100:

**Comment by SaraJaoude** [comment]
Thanks @schmelto and @kaiwalyakoparkar ! Still trying to learn and making a lot of mistakes- I have only ever been a lawyer up to a month ago! :)

**Comment by starlightknown** [comment]
wow that is amazing multitasking and great speed of learning. Thank you for making such a great site in short time 🚀

**Comment by kaiwalyakoparkar** [comment]
@SaraJaoude You are doing great. That is really cool! :sunglasses: .
