### ISSUE TITLE
[Doc] Frequently Asked Questions

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/EddieHubCommunity.github.io#178]
## Points to improve on
Taking the last answer as an example,
```
I just joined, why can't I not post links on Discord?

You have recently joined the community and you have tried to share a link, but found that NightBot has deleted this message. We appreciate that the community is a place to share your work, which we encourage only for our regular community members (aka “Team Eddie”). To become a regular and get the role "Team Eddie", we highly suggest to get involved in the community conversation and add value by helping other community members.
```
- Grammatical Errors (eg: `can't I not` - double negatives, doesn't match the answer)
- Non-inclusive language (eg: `we encourage only our regular community` - implies that we hold a bias against newcomers)
- Short term fixes ignored (eg: `Gists` and `Discussions` allow newcomers to share links)

## Suggested fixes

- [ ] Fix grammatical errors
- [ ] Review the section (The more people reviewing it, the better)
- [ ] Add short term solutions with links/examples as needed

For example, the last FAQ could be:
```
I just joined, why can't I post links on Discord?

You've just joined the community and want to share a link - only to get an error with the flag "NightBot has deleted this message"
While the community is a place to share your work, we limit links (other than GitHub) to our regular community members with the role “Team Eddie”. To get this role, you need to participate in the conversation. Add value by helping other community members. Until then, you can use Gists to share relevant external links!
```

**Comment by SaraJaoude** [comment]
Grammatical error fixed

**Comment by cl507iff** [comment]
Is the inclusive language issue fixed? If not I could fix it.

**Comment by eddiejaoude** [comment]
oops yes this is fixed, we should close the issue 👍 thank you for letting us know

We discussed some open source contributions in our Discord today if you are looking for some http://discord.eddiehub.org
