### ISSUE TITLE
[ SEO ] Sitemap absent on the website

### ISSUE THREAD

**Issue by AnirudhPanda** [EddieHubCommunity/EddieHubCommunity.github.io#180]

**Comment by schmelto** [comment]
Could you add some more information about this topic?

**Comment by AnirudhPanda** [comment]
> Could you add some more information about this topic?

A **sitemap** is a blueprint of your website that helps search engines find, crawl, and index all of your website's content.
After a sitemap.xml is generated it is added to the root folder of the website and then indexed in the google search console(require admin access by putting a line of code in head tag in HTML)

**Comment by eddiejaoude** [comment]
The EddieHub website is only 1 page, not sure a site map is needed?

**Comment by AnirudhPanda** [comment]
> The EddieHub website is only 1 page, not sure a site map is needed?

It's fairly important to have a sitemap for optimization. it is easier for bots or crawlers to read web page data in a more efficient way. The ranking is already comprised because of the use of more images, text, page sections

**Comment by eddiejaoude** [comment]
I think it will be a sad and lonely site map though, would it not be like this

```
_
 |_ home
```

Or do you mean it is important to have the file?

**Comment by AnirudhPanda** [comment]
> I think it will be a sad and lonely site map though, would it not be like this
> 
> ```
> _
>  |_ home
> ```
> 
> Or do you mean it is important to have the file?

Good to have! Not a major issue though

**Comment by eddiejaoude** [comment]
Ah ok, if it is good to have, even if a small entry, lets do it 👍

**Comment by xkrishguptaa** [comment]
Since we are using next.js now, this is what we have to do:

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generate-a-sitemap

- **app/sitemap.js**

```ts 
export default function sitemap() {
  return [
    {
      url: 'https://eddiehub.org',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
  ]
}
```

Marking this as a good-first issue as only this file has to be created
