### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/EddieHubCommunity.github.io#182]
![Screenshot_20210601_215056.jpg](https://user-images.githubusercontent.com/30869493/120382033-78a0ae00-c323-11eb-8b7d-0cb2e8a17150.jpg)

Should be https I think

**Comment by eddiejaoude** [comment]
hey @schmelto thanks for raising. Can you clarify where this screenshot was taken from, could you take it of the whole page? Because where I thought it was taken from, the link works for me

**Comment by schmelto** [comment]
> hey @schmelto thanks for raising. Can you clarify where this screenshot was taken from, could you take it of the whole page? Because where I thought it was taken from, the link works for me

It was on the main screen of the repo but I think it's a issue with my browser. It makes a https link out of it. Don't know exactly why...
So on my laptop link works on my phone not cause of the browser issue appending http to https..
