### ISSUE TITLE
Moderators div are not aligned properly

### ISSUE THREAD

**Issue by WebShivam** [EddieHubCommunity/EddieHubCommunity.github.io#184]
Here is the screenshot 👇 
![eddie-mod-section](https://user-images.githubusercontent.com/64413107/120836511-455c5a00-c583-11eb-8b14-89b87f8a8bea.jpg)

**Comment by adityaraute** [comment]
Because Alexander's name is on two lines. Something surely needs to be done. But that will increase the height of all cards in the second row, so inconsistencies galore.

**Comment by eddiejaoude** [comment]
> inconsistencies galore

@adityaraute this is not collaborative language, I would have expected more from you 😞

**Comment by SaraJaoude** [comment]
This is a duplicate of:
https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/170
