### ISSUE TITLE
Code of Conduct link not found

### ISSUE THREAD

**Issue by Utkarsh299-tech** [EddieHubCommunity/EddieHubCommunity.github.io#186]
The **Code of Conduct** link in README.md file is not found. It's giving error 404.

Link to the repository: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/main/README.md

Screenshot: 
![Screenshot (181)](https://user-images.githubusercontent.com/60184229/120928931-600a0c80-c704-11eb-90cf-0fcb2d7ae284.png)

**Comment by starlightknown** [comment]
There is no code of conduct in files, maybe another issue can be opened for it

**Comment by gouravmohanty7070** [comment]
Hey! Can I work on it?

**Comment by Panquesito7** [comment]
> Hey! Can I work on it?

Sure! Feel free to create a PR, and maintainers will review it. 🙂

**Comment by gouravmohanty7070** [comment]
@Panquesito7 Can you please brief from where is the code of conduct file missing. Because it seems to work perfectly fine in the readme section!

**Comment by Panquesito7** [comment]
It seems this issue is already solved. Can someone close it, please?
Thanks for pointing that out, @gouravmohanty7070! 😄

**Comment by Utkarsh299-tech** [comment]
Since this issue is already solved, I'm closing it. Thank you, everyone!
