### ISSUE TITLE
Add Code of conduct

### ISSUE THREAD

**Issue by starlightknown** [EddieHubCommunity/EddieHubCommunity.github.io#187]
There is no code of conduct in the repo but a link is present which gives 404, ref #186

**Comment by Vyvy-vi** [comment]
Maybe this would be a good time for us to consider community health files in a `.github` repo?
(https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

**Comment by eddiejaoude** [comment]
Thanks for raising 👍 . We can use the `support` CoC everywhere https://github.com/EddieHubCommunity/support/blob/main/CODE_OF_CONDUCT.md

**Comment by xkrishguptaa** [comment]
I believe we have one which is inherited from `.github` and directly integrated in the UI for this repo now. https://github.com/EddieHubCommunity/EddieHubCommunity.github.io?tab=coc-ov-file#coc-ov-file

Therefore closing this! Thank you for raising though
