### ISSUE TITLE
EddieHub blog tutorial link broken

### ISSUE THREAD

**Issue by importhuman** [EddieHubCommunity/EddieHubCommunity.github.io#189]
[This blog post on getting started](https://www.eddiejaoude.io/blog-may-2021-joining-eddiehub) is mentioned on the homepage, but is broken due to a typo.

Edit: https://www.eddiejaoude.io/blog-may-2021-joining-eddihub needs to be replaced with https://www.eddiejaoude.io/blog-may-2021-joining-eddiehub

**Comment by schmelto** [comment]
Due the website is moved to a low code platform I think only @SaraJaoude can do this :)

**Comment by importhuman** [comment]
@schmelto I realized later that it's been moved. Thanks!

**Comment by eddiejaoude** [comment]
Oh thank you for logging the bug 👍 we will look at it now

**Comment by eddiejaoude** [comment]
We checked and it seems to work, is it the link at the top of the page? https://www.eddiejaoude.io/blogs

**Comment by eddiejaoude** [comment]
Oh you are right, thank you for logging 👍 

<img width="1565" alt="Screenshot 2021-06-26 at 18 32 36" src="https://user-images.githubusercontent.com/624760/123521169-fd75b200-d6ac-11eb-967c-275c0745e553.png">

**Comment by eddiejaoude** [comment]
Should be fixed now. Thank you again for letting us know 🤓
