### ISSUE TITLE
Invite me to the organization

### ISSUE THREAD

**Issue by RAHUL-KAD** [EddieHubCommunity/EddieHubCommunity.github.io#191]
Hey looking forward to be part of your community.

**Comment by schmelto** [comment]
Hey @RAHUL-KAD  you can create an issue in the support repo for that

**Comment by adityaraute** [comment]
@RAHUL-KAD What's the update here?

**Comment by RAHUL-KAD** [comment]
I am looking for a machine learning or deep learning community. Do you have this community?

**Comment by adityaraute** [comment]
Not specifically. We are an open source community with members whose proficiencies range through all wings of tech. You'll surely find some people with similar interests as yours.

**Comment by eddiejaoude** [comment]
I am going to closed this issue, @RAHUL-KAD please create an issue with the relevant type as suggested by @schmelto 

For more information please see https://www.eddiejaoude.io/blog-may-2021-joining-eddiehub
