### ISSUE TITLE
Issue with padding for yt video on mobile

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/EddieHubCommunity.github.io#192]
![Screenshot_20210721_095237_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/126452288-575eb89a-390a-4a28-acf8-a4714420c7b1.jpg)

**Comment by adityaraute** [comment]
Yeah the left margin/padding needs to be adjusted for mobile view.

**Comment by cadmaus** [comment]
Hello, I am new here, is the issue resolved or should I look into it? Also if I should can someone help me get started

**Comment by schmelto** [comment]
> Hello, I am new here, is the issue resolved or should I look into it? Also if I should can someone help me get started

Hey @cadmaus , unfortunately the website is moved to a low code platform. Therefore only @SaraJaoude or Eddie can do those changes I think.

**Comment by cadmaus** [comment]
Oh okay, Thank you for the reply @schmelto

**Comment by SaraJaoude** [comment]
We had trouble with the low code template so we have now used another one.  We have checked it on mobile and desktop and this appears to look much better.  Now this is resolved I will close this issue. 

![Screenshot 2021-07-28 at 10 20 28](https://user-images.githubusercontent.com/82668196/127297817-1ee35c7d-765a-42cb-9a00-86fcd744a8b8.png)

**Comment by eddiejaoude** [comment]
Great team work everyone 👍 - looks better now 💥
