### ISSUE TITLE
Adding Back to top button 

### ISSUE THREAD

**Issue by vishal-codes** [EddieHubCommunity/EddieHubCommunity.github.io#193]
Can we add a back to top button.

**Comment by gouravmohanty7070** [comment]
Hey can I take up the issue?

**Comment by SaraJaoude** [comment]
Hi @gouravmohanty7070 the EddieHub website is done through a low code platform that only Eddie Jaoude and I can make amendments too. 

The back to top button has been added and I am therefore closing this issue.
