### ISSUE TITLE
EddieHub's Newsletters page is Irresponsive  

### ISSUE THREAD

**Issue by divyanshraj0408** [EddieHubCommunity/EddieHubCommunity.github.io#195]
[eddiejaoude.io/newsletter-june-2021](https://www.eddiejaoude.io/newsletter-june-2021)
This page is **not responsive** , and **May Month's Newsletter is facing the same issue**. Kindly look into it, i hope my suggestion helps.
I have attached the screen shot of the May's NewLetter.
![EddieHub Newsletters — Firefox Developer Edition 29-08-2021 01_23_05](https://user-images.githubusercontent.com/73312468/131229500-84e7f2af-df7b-49cb-8ab0-b93006a7e76a.png)

**Comment by SaraJaoude** [comment]
As the newsletter initially goes out via email to those that have subscribed, we have to use legacy code to work in the majority of email clients. Therefore we lose a lot of modern functionality - we will keep looking into this.

**Comment by xkrishguptaa** [comment]
Hi! We are no longer using Katra, therefore this issue should've been resolved :)
