### ISSUE TITLE
Change the website's title to `EddieHub`

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/EddieHubCommunity.github.io#197]

**Comment by gouravmohanty7070** [comment]
Can I work on it?

**Comment by eddiejaoude** [comment]
> Website built using Kartra a low code platform. Please use Issues here to track ideas / improvements / suggestions / bugs etc.

@gouravmohanty7070 please see this from he readme

**Comment by eddiejaoude** [comment]
Currently it is 

```html
<title>eddiehub-home</title>
```

and yes we should change it to 

```html
<title>EddieHub Community</title>
```

**Comment by Sin-Sumit** [comment]
Hey @eddiejaoude where are the files?

**Comment by Sin-Sumit** [comment]
In code it has index.html

**Comment by eddiejaoude** [comment]
> Website built using Kartra a low code platform. Please use Issues here to track ideas / improvements / suggestions / bugs etc.

@Sin-Sumit please check the text above from the readme, if it is not clear please let us know and it can be updated in the readme.

**Comment by Sin-Sumit** [comment]
@eddiejaoude The readme text states that the website is built using the Kartra, then how I can change the title?

**Comment by eddiejaoude** [comment]
@Sin-Sumit that is my point, unfortunately you cannot change it. This repo is for issuing tracking only. I will update the readme message to avoid confusion

**Comment by Sin-Sumit** [comment]
Yup, all clear now.

**Comment by Sin-Sumit** [comment]
@eddiejaoude if this issue is only for tracking then why was asked to change the title.

**Comment by eddiejaoude** [comment]
> if this issue is only for tracking then why was asked to change the title.

I do not see where this happened, where were you asked to change this?

**Comment by Sin-Sumit** [comment]
It is mentioned in issue197 "Change the website's title to EddieHub".

**Comment by eddiejaoude** [comment]
Yes, because this is the issue tracking for the website, but you were not ask to change it because you cannot change it, unfortunately only we can change it.

**Comment by Sin-Sumit** [comment]
Yes, it is mentioned for a change, which actually does not needs to change, I was confused earlier about what to change and I know how to change but where I will do those changes.  But now, I got you can only change and I can't change.

Thank you for the above messages exchange.

**Comment by eddiejaoude** [comment]
I have now updated this...

<img width="1043" alt="Screenshot 2021-09-01 at 14 20 10" src="https://user-images.githubusercontent.com/624760/131678539-50523c1e-9c75-455d-9873-3fb7e032408a.png">

**Comment by Panquesito7** [comment]
@eddiejaoude, thanks for updating it. I think it'd be better if it could be changed to `EddieHub - Inclusive Open Source community`. Let me know what do you think, thanks. 🙂
