### ISSUE TITLE
How can I join your team

### ISSUE THREAD

**Issue by FirdausJawed** [EddieHubCommunity/EddieHubCommunity.github.io#203]
I am really eager to join your team

can you please tell me the procedure!! how can i join it and what are the criteria to be a team member here

**Comment by FirdausJawed** [comment]
I wanna join join the team not only the organisation

**Comment by eddiejaoude** [comment]
Hi, please do not spam the same message, people live in different timezones and usually do this for free.

We add people to the teams after they add a lot of value to the community. Please look at adding value first

**Comment by FirdausJawed** [comment]
_ok, thanks_
