### ISSUE TITLE
DataStax in Eddiehub website

### ISSUE THREAD

**Issue by SriSatyaT** [EddieHubCommunity/EddieHubCommunity.github.io#206]
The alignment of DataStax in Sponsor section. Aligning towards center might effect eddiehub moscout. So it looks good only if the moscout is above the Subline "we are sponsored by" or below the "Sign up now for free to DataStax's NoSQL serverless Open Source database!" 
![SriSatyaT ( Sri Satya) - Google Chrome 14-09-2021 10_05_58_LI](https://user-images.githubusercontent.com/78905067/133197199-51fa781b-0187-42ee-8048-a4e1c63e31f3.jpg)

**Comment by SaraJaoude** [comment]
Thanks for the feedback - unfortunately this is one of the limitations of using a low code platform and their templates (which can be a bit restrictive).  We will look into this.

**Comment by SriSatyaT** [comment]
> Thanks for the feedback - unfortunately this is one of the limitations of using a low code platform and their templates (which can be a bit restrictive).  We will look into this.

Alright. Thought it would be a good first issue for noobs in open source 😅.

**Comment by SriSatyaT** [comment]
> Thanks for the feedback - unfortunately this is one of the limitations of using a low code platform and their templates (which can be a bit restrictive).  We will look into this.

Alright. Thought it would be good first issue for the folks who wanted to start their open source journey in Eddiehub 😅.

**Comment by SaraJaoude** [comment]
As we are using a low code platform, the EddieHub website can only be updated by Eddie Jaoude and I. We have this repo for issue tracking only :) 

Good repos for people to get started are: 

- https://github.com/EddieHubCommunity/hacktoberfest-practice
- https://github.com/EddieHubCommunity/LinkFree

**Comment by SriSatyaT** [comment]
> As we are using a low code platform, the EddieHub website can only be updated by Eddie Jaoude and I. We have this repo for issue tracking only :) 
> 
> Good repos for people to get started are: 
> 
> - https://github.com/EddieHubCommunity/hacktoberfest-practice
> - https://github.com/EddieHubCommunity/LinkFree
> 

Thanks Sara for the info.

**Comment by eddiejaoude** [comment]
Closing this issue as DataStax is no longer a sponsor
