### ISSUE TITLE
Typo in Community Call Sign Up page

### ISSUE THREAD

**Issue by guptasajal411** [EddieHubCommunity/EddieHubCommunity.github.io#207]
I noticed a typo in `Community Classroom` in the community call sign up page
Link: https://www.eddiehub.org/community-call-sign-up
Screenshot:
![image](https://user-images.githubusercontent.com/70312106/134669859-c92de352-4fd1-457c-a7e8-f8f32fd71a66.png)

**Comment by SaraJaoude** [comment]
Thanks @guptasajal411.  I have now resolved this
<img width="1016" alt="Screenshot 2021-09-24 at 12 53 42" src="https://user-images.githubusercontent.com/82668196/134670158-89e2d56a-58ee-45a3-832a-6a0ea7722df2.png">
.

**Comment by guptasajal411** [comment]
Thanks for the quick response 💥
