### ISSUE TITLE
Anchor tags missing 

### ISSUE THREAD

**Issue by tanishagupta1** [EddieHubCommunity/EddieHubCommunity.github.io#208]
![Screenshot (2655)](https://user-images.githubusercontent.com/73746588/135234067-bdd4c52d-bceb-4e30-a94f-a6e44c31147b.png)

Links to Newsletter and LinkedIn are absent in aforementioned section in the image

**Comment by SaraJaoude** [comment]
Thank you for your contribution.  This has now been done.
