### ISSUE TITLE
Feature Request- UI Improvement for Hacktoberfest page

### ISSUE THREAD

**Issue by manavmodi22** [EddieHubCommunity/EddieHubCommunity.github.io#209]
Checked out the site https://www.eddiehub.org/hacktoberfest-2021 . 
![image](https://user-images.githubusercontent.com/55242552/135656542-576da47b-1dba-4614-a63f-eff50263f4e9.png)
The timeline could be improved by:

1. Adding links to each video/streams.
2. Calendar invite
3. Progress indicators like green ticks indicating that the stream is already over.

**Comment by SaraJaoude** [comment]
Thank you for the suggestions.  

1. It is very difficult to create these in advance given that we are dependent on the guests confirming their presence and providing the information we need. 
2. We will look into this in the future, but in the meantime there is always the facility to set a reminder. 
3. Unfortunately this is not easily done to integrate with YouTube. Given that the time and date is on the schedule this will need serve as an indication as to whether an event has taken place or not.

Be sure to join the discussion on [Discord](https://discord.com/invite/jZQs6Wu) where we will keep you updated on upcoming events.
