### ISSUE TITLE
Unable to see the captcha code on newsletter sign up

### ISSUE THREAD

**Issue by lmac-1** [EddieHubCommunity/EddieHubCommunity.github.io#213]
### Description

When signing up for the newsletter on [Eddie Hub](https://www.eddiehub.org/), I couldn't see the captcha code. 

Browser: Google Chrome (Version 95.0.4638.54)
OS: MacOS Big Sur Version 11.6

It works fine on Firefox (v92).

### Screenshots

<img width="692" alt="Screenshot 2021-10-26 at 18 57 47" src="https://user-images.githubusercontent.com/64803272/138977665-20b9cb0a-c495-4056-9e8e-93ceb0f02d66.png">

If I zoom in, it appears to be there but in a very light gray colour that is unreadable:

<img width="474" alt="Screenshot 2021-10-26 at 19 00 53" src="https://user-images.githubusercontent.com/64803272/138977781-864220a0-edba-48c8-9a08-8c29043724ef.png">

**Comment by lmac-1** [comment]
Hi everyone, I was just on the EddieHub website again (using Google Chrome as before) and I can see the Captcha code. I can no longer replicate this issue. 

![image](https://user-images.githubusercontent.com/64803272/151889315-f189ce06-2eb6-4f43-9987-118c21b60971.png)

Not sure if you want to close the ticket.

**Comment by eddiejaoude** [comment]
Ok thanks Lucy, we will close for now. If it occurs again we can reopen it. Thanks for following up 👍
