### ISSUE TITLE
Navbar not responsive for tablet size

### ISSUE THREAD

**Issue by ZaidKhan2002** [EddieHubCommunity/EddieHubCommunity.github.io#214]
### Description

Navbar is not responsive for tablet size and all the elements are misplaced. I should have toggle button for tablet size and should be straight for big screens such as laptop. 

### Screenshots

<img width="883" alt="Screenshot 2021-11-05 at 8 05 01 PM" src="https://user-images.githubusercontent.com/71960989/140528238-a35b5ee7-d4df-4794-848d-1a333bbcb652.png">

**Comment by SaraJaoude** [comment]
Thank you for raising.  I have now addressed this by adding a button for the brochure.


<img width="682" alt="Screenshot 2021-11-06 at 10 08 29" src="https://user-images.githubusercontent.com/82668196/140605911-e343703e-21d7-4421-af26-a5ac298c52d9.png">

I will now close this issue.
