### ISSUE TITLE
[FEATURE] Add my testimonial!

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/EddieHubCommunity.github.io#216]
### ⭐ Suggestion

EddieHub is the place where my journey began, EddieHub tries to help everyone in every possible way they can! I didn't even know how to code when I joined, now am skilled enough to help other people. I love the gesture of the community, the community is built over strong pillars. Love how the community is really friendly, everyone is up for helping anyone. Eddie is awesome, the moderators are awesome and the community comprising all of this, plus really friendly members is even awesome 😄

**Comment by Panquesito7** [comment]
You can also add your testimonial in the following
discussion, by the way 😃 https://github.com/EddieHubCommunity/support/discussions/1618

**Comment by krishguptadev** [comment]
To the discussion thread instead.
