### ISSUE TITLE
[FEATURE] Update COC to v2.1

### ISSUE THREAD

**Issue by krshkodes** [EddieHubCommunity/EddieHubCommunity.github.io#219]
### ⭐ Suggestion

Update the Code of Conduct from the official site: https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by Vidit-Ostwal** [comment]
Shall I work on this?

**Comment by krishguptadev** [comment]
> Shall I work on this?

sure!

**Comment by eddiejaoude** [comment]
PR #222  got merged
