### ISSUE TITLE
[FEATURE] Update Email in Code of Conduct

### ISSUE THREAD

**Issue by krshkodes** [EddieHubCommunity/EddieHubCommunity.github.io#220]
### ⭐ Suggestion

![image](https://user-images.githubusercontent.com/91655303/143671437-15b106b0-b0ea-47f0-a35a-15a2cb529989.png)

**Comment by salmantec** [comment]
Shall I pick this ?

**Comment by Panquesito7** [comment]
> Shall I pick this ?

Feel free to work on it! 😄

**Comment by Kannav02** [comment]
has this issue been fixed?

**Comment by Panquesito7** [comment]
> has this issue been fixed?

There are various open PRs for this https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/pulls but no, it hasn't been fixed yet.

**Comment by Kannav02** [comment]
Can I contribute to it then?

**Comment by Evavic44** [comment]
> Can I contribute to it then?

I think what @Panquesito7 is trying to say is that there are a lot of fixes for this that haven't been merged.

**Comment by Kannav02** [comment]
Oh okay

**Comment by salmantec** [comment]
Yeah I think, I have already raised PR for this issue. @Panquesito7  Please check.

**Comment by eddiejaoude** [comment]
PR #221  was merged, closing issue
