### ISSUE TITLE
David Leal missing from mods section

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/EddieHubCommunity.github.io#223]
### Description

I think, David Leal (@Panquesito7) is a mod of EddieHub too, but I can't see his name under the mods section.

**Comment by Panquesito7** [comment]
Hey there! Nope, I'm not a moderator for EddieHub 😅 just a repository maintainer.

**Comment by KendallDoesCoding** [comment]
> Hey there! Nope, I'm not a moderator for EddieHub 😅 just a repository maintainer.

Oh ok, btw you messed up the Youtube icon in my README with your PR, I think. Please restore branch and I will revert changes.
