### ISSUE TITLE
[DOCS] Membership clarification

### ISSUE THREAD

**Issue by MarieTKD** [EddieHubCommunity/EddieHubCommunity.github.io#231]
### Description

Add to the FAQ "How to become a member" with a link to the invite

**Comment by eddiejaoude** [comment]
Thanks @MarieTKD 

@SaraJaoude can you add another FAQ to the EddieHub.org website, for people to fill in this form to get an automatic invite to the EddieHub GitHub Org

Please also add they need to make it `public` if they want it to appear on their profile, by default it is `private`

https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

**Comment by SaraJaoude** [comment]
The website has now been updated. See screenshot:

<img width="1167" alt="Screenshot 2022-05-24 at 16 32 30" src="https://user-images.githubusercontent.com/82668196/170075183-473a0d31-4765-4c3b-91f4-955b1847823c.png">

I will now close this.
