### ISSUE TITLE
Request To Join the COMMUNITY!!![OTHER]

### ISSUE THREAD

**Issue by franklinscripts** [EddieHubCommunity/EddieHubCommunity.github.io#234]
### Request to join the community
** Hi my name I franklin**, I am a junior frontend developer , started my career late 2021.
I am looking forward to join this community so as to improve my background on the industry and to explore more fields in tech
@eddiejaounde I am looking forward for an invitation.. Thanks.

**Comment by eddiejaoude** [comment]
Sure, you can add yourself to the Organisation and also get started contributing to open source by following the steps in our GitHub Org, any questions or improvements let us know https://github.com/EddieHubCommunity?view_as=public
