### ISSUE TITLE
REQUEST TO JOIN COMMUNITY 

### ISSUE THREAD

**Issue by chikaazuonwu** [EddieHubCommunity/EddieHubCommunity.github.io#235]
### Description

Hi 
My name is Chika Azuonwu and am interested in joining your community to become a member. I want to learn coding and tech from members of this community.

**Comment by EmuSmith** [comment]
Hello, I am Smith Emu Utethe, i want to be a part of this project. I saw your interest in Front-End and I do know i can benefit from this community to better the world.

**Comment by eddiejaoude** [comment]
Great, yes join us! We have more information on our website http://eddiehub.org and also our GitHub Org README has steps to follow 

https://github.com/EddieHubCommunity?view_as=public
