### ISSUE TITLE
REQUEST TO JOIN THE COMMUNITY

### ISSUE THREAD

**Issue by Samruddhiiii** [EddieHubCommunity/EddieHubCommunity.github.io#236]
### What would you like to share?

HEY! 
My name is Samruddhi, I am an Open source enthusiast and really following the community on youtube for a very long time. And now looking to join you as well on Github. I want to learn coding and tech from members of this community.

**Comment by Samruddhiiii** [comment]
add to me in organisation

**Comment by eddiejaoude** [comment]
Hi @Samruddhiiii , welcome 👋 

Sure, you can add your and also get started contributing to open source by following the steps in our GitHub Org, any questions or improvements let us know https://github.com/EddieHubCommunity?view_as=public
