### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Decryptus007** [EddieHubCommunity/EddieHubCommunity.github.io#239]
### What would you like to share?

**I would like to join this amazing community**

**Comment by rajneesh-18** [comment]
Closed or not ?

**Comment by eddiejaoude** [comment]
Thanks @rajneesh-18 , yes we can close, they need to raise it on the `support` repo and the GitHub Action will send them an invite

**Comment by rajneesh-18** [comment]
Cool
