### ISSUE TITLE
Ambassador program -  accordion not working properly

### ISSUE THREAD

**Issue by Aniket1026** [EddieHubCommunity/EddieHubCommunity.github.io#247]
### Description

The accordion of the ambassador program is not working properly . Although all the questions are answered correctly in detail but the last question of the last section is already opened and even after clicking the arrow to close , it is not even closing. 
If it is kept like this for any reason ? I'd love to know. If not then I think we can improve this . Below I'll be attaching the screenshots for reference . 

Thank you 😄

### Screenshots

The accordion is already open

![Screenshot (124)](https://user-images.githubusercontent.com/92184189/201520244-4d405203-845d-4b98-8db7-375d138fb87f.png)

After clicking the arrow key to close it is still open

![Screenshot (125)](https://user-images.githubusercontent.com/92184189/201520250-074bffd1-08c3-420b-bec8-a039b43faf11.png)

**Comment by SaraJaoude** [comment]
As all pages on the eddiehub.org domain are created using a low code platform, only myself and Eddie Jaoude can make changes to these. 

Thank you for bringing this to our attention, this has now been resolved (see screenshot) so I will be closing this issue.

<img width="1121" alt="Screenshot 2022-11-13 at 13 50 55" src="https://user-images.githubusercontent.com/82668196/201525545-d30b88ec-ec64-440a-9ec6-e62d9f43306c.png">

**Comment by Aniket1026** [comment]
Sure @SaraJaoude I was aware that I couldn't contribute by myself . I was just to bring your attention on this issue so that it gets resolved . I'm glad that I was able to help by any means.

Thank you 😄

**Comment by eddiejaoude** [comment]
thanks @Aniket1026 and @SaraJaoude 👍
