### ISSUE TITLE
[FEATURE] "How to Contribute" Feature

### ISSUE THREAD

**Issue by AftabAhmedAbro** [EddieHubCommunity/EddieHubCommunity.github.io#248]
### Description

As an open-source community, EddieHub needs to make paths for new open-source contributors to add value to this community through well-defined guidelines on github.
If any new contributor wants to contribute, then as other communities define their guidelines on making pull requests or joining the organization, EddieHub also needs to take a step to make it accessible on GitHub.

**Comment by eddiejaoude** [comment]
Hi @AftabAhmedAbro, could you elaborate a bit more about what you mean? We have these steps in our GitHub Org for people to onboard with our EddieHub community and also contributing to multiple projects.

<img width="1014" alt="Screenshot 2022-12-18 at 16 38 18" src="https://user-images.githubusercontent.com/624760/208309295-5f408bf4-0b4f-4bef-b94b-c4e600277807.png">

**Comment by AftabAhmedAbro** [comment]
But this is not visible to me even I am a member of the organization 

![image](https://user-images.githubusercontent.com/73740818/208321315-d0cbb1bf-f921-424c-98e6-bb9157a0133b.png)

**Comment by eddiejaoude** [comment]
If you view it as a member it is not displayed but if you view it not as a member with this link (you have the option on the right) http://github.com/EddieHubCommunity/?view_as=public

Are you suggesting to have it on both? I am trying to understand what you are suggesting

**Comment by AftabAhmedAbro** [comment]
Thanks for guiding me!! @eddiejaoude
