### ISSUE TITLE
Moderators section last-right card is not uniformly aligned.

### ISSUE THREAD

**Issue by Abhishek-00** [EddieHubCommunity/EddieHubCommunity.github.io#251]
### Description

In the Moderators section there is some spacing issue inside the cards they are not align properly.

### Screenshots

![image](https://user-images.githubusercontent.com/101923614/213965805-95b4fd92-be1c-46b6-9a10-fefde7c39e40.png)

**Comment by SaraJaoude** [comment]
The webpage is done via a low code website and this is a change we cannot easily make.  I will therefore be closing this issue.
