### ISSUE TITLE
HTTPS broken on discord.eddiehub.org

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/EddieHubCommunity.github.io#256]
### Description

HTTPS broken on discord.eddiehub.org

It is fine with HTTP or just as is in browser but if you have https:// on the URL it won't work.

### Screenshots

![image](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/19922556/8c0a4eea-b262-4053-8eae-6e079c70dd11)

**Comment by KaKashi1210** [comment]
it is working on my machine

**Comment by loftwah** [comment]
> it is working on my machine

```bash
 ✘ ❯  ~/gits/public_html   master  curl https://discord.eddiehub.org
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to discord.eddiehub.org:443
```

**Comment by eddiejaoude** [comment]
I get an error also

**Comment by loftwah** [comment]
This is still broken for what should be a very simple fix.

**Comment by loftwah** [comment]
Eddie has fixed this.

**Comment by eddiejaoude** [comment]
Thanks Dean!
