### ISSUE TITLE
[FEATURE] Testimonials

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#258]
### Description

note: for profile images use their GitHub magic url `github.com/<username>.png` for example GitHub.com/eddiejaoude.png

Move from 

<img width="1268" alt="Screenshot 2023-11-03 at 11 31 34" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/624760/ec8df1e1-3052-4b82-b5ad-8cceed446e7e">

To

<img width="1263" alt="Screenshot 2023-11-03 at 11 31 41" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/624760/66f22cba-2f6a-429e-9cd7-e219d8147881">

**Comment by luckyklyist** [comment]
Can you assign this issue to me ?

**Comment by eddiejaoude** [comment]
Sure 👍  I have assigned it to you - please note as we discussed on the Discord community call, this is time critical, let us know if you can't get it done today

**Comment by xkrishguptaa** [comment]
This is complete in #273  I belive ✅
