### ISSUE TITLE
[FEATURE] Update the logo with the EddieHub Mascot

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/EddieHubCommunity.github.io#265]
### Description

https://github.com/EddieHubCommunity/Branding

![](https://user-images.githubusercontent.com/624760/280271206-72a574e7-bf10-470c-9ef8-09e1f3baf2f0.png)

Concerned file: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/main/src/images/logos/eddiehub.png

**Comment by ninadvyas** [comment]
hello @xkrishguptaa, can i work on this issue?
