### ISSUE TITLE
Use NextJS image component for mods

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#274]
### Description

Change from `img` to `<Image` https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/ab69354c3d11147f5b6677918433b700b3f4ca8a/src/components/Moderators.jsx#L94C14-L94C14

**Comment by xkrishguptaa** [comment]
Fixed in #278!
