### ISSUE TITLE
[FEATURE] Renamed nav link from "features" to "projects"

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#281]
### Description

[FEATURE] Renamed nav link from "features" to "projects"

**Comment by sandramsc** [comment]
Hi, can I have this assigned to me please?

**Comment by eddiejaoude** [comment]
Sure, assigned

**Comment by eddiejaoude** [comment]
Sorry Sandra, I completed the issue because we needed it to deploy to production
