### ISSUE TITLE
Dummy text for GitHub Feature

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/EddieHubCommunity.github.io#289]
### Description

<img width="765" alt="image" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/135469703/52ed55f9-c0c9-4862-8e65-4970fe85c379">

Update this dummy text

**Comment by Devanshukoli** [comment]
- oh? Then what should we write on it?

can you provide something for that?

**Comment by eddiejaoude** [comment]
Thanks Krish!

I have assigned this to me, because I made the changes already but forgot to push
