### ISSUE TITLE
[FEATURE] Founders section?

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#290]
### Description

Do we need to add the founders section?

<img width="1226" alt="Screenshot 2023-11-03 at 17 33 34" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/624760/abb347e6-69b3-4edd-a0ab-32e2c07096b4">

**Comment by Satoshi-Sh** [comment]
Can I take this task? I need the links to the videos (I couldn't find them on Youtube).

**Comment by xkrishguptaa** [comment]
Hi @eddiejaoude can you share the needed information?

**Comment by eddiejaoude** [comment]
Sure, thanks @xkrishguptaa 👍  Sorry @Satoshi-Sh I should have included the YouTube links 🤦‍♂️ 

- https://youtu.be/RnH9udLsAKk
- https://youtu.be/eWetvRusfUU

**Comment by Satoshi-Sh** [comment]
Great. Thanks for your help. I will work on this issue soon. :+1:
