### ISSUE TITLE
[FEATURE] Update DNS for EddieHub.org

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#293]
### Description

What else needs updating?

- website
- short links?
   - discord `discord.eddiehub.org`
   - GitHub `GitHub.eddiehub.org`

**Comment by xkrishguptaa** [comment]
These links are working Eddie, I don't know what you mean

**Comment by eddiejaoude** [comment]
if they are woking, we can close 👍  thank you
