### ISSUE TITLE
[FEATURE] Add LinkedIn/Twitter(X)

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubCommunity.github.io#298]
### Description

Add linkedIn and twitter icons linking to the eddiehub org and eddies profile

Location on old site for refernce
![header](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/97615019/860e62ee-77ef-488d-9b65-a58ddb9b531a)

For this issue, place the icons on the bottom of the page next to the discord and github icons

**Comment by Devanshukoli** [comment]
- In the [eddihub](https://www.eddiehub.org/) website it's in footer, And I was wondering if for [linkedin](https://www.linkedin.com/company/eddiehub/) and [twiiter/x](https://twitter.com/eddiejaoude) .  we can put this links to them?

What do you think about this? @amandamartin-dev

**Comment by Devanshukoli** [comment]
- Though, I tried in my local machine and it looked like below 
- 
![image](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/99028806/69178723-1195-4b56-b60a-a32130289ee0)

- What are your thoughts on this?

**Comment by Devanshukoli** [comment]
@xkrishguptaa Yup, why not? Font awesome ?

**Comment by TechBond7** [comment]
@xkrishguptaa Please assign this task to me.

**Comment by xkrishguptaa** [comment]
I think @Devanshukoli is working on this, if they aren't we can assign yoh @TechBond7

**Comment by Devanshukoli** [comment]
Actually, please go and assigned them.

**Comment by xkrishguptaa** [comment]
Thank you @Devanshukoli! @TechBond7 assigning you!

**Comment by TechBond7** [comment]
@xkrishguptaa I've made a pull request for this feature. 
Please check it out and let me know your feedback.
Thank you.
