### ISSUE TITLE
Video with 1 sentence with people from the community

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#3]
My idea was to create a video we can put along side our mission statement, include 1 sentence from different people from the community

What do you think? Would you take part?

**Comment by gagangaur** [comment]
similar to a kind of video which was put on hacktoberfest website

**Comment by eddiejaoude** [comment]
@gagangaur yes similar, but I don't want to split sentences up like they did, I think it would be 1 complete sentence from each person before the video moves on

**Comment by gagangaur** [comment]
Content in the video should be narrated like a story what do you think upon this

**Comment by eddiejaoude** [comment]
This is a good idea, but more difficult to do 😂 - a lot of planning.

Maybe for the 2nd version. I was thinking to keep it simple for the first version. But we can try because a story is best 👍

**Comment by kaiwalyakoparkar** [comment]
@eddiejaoude This is a great idea!

**Comment by Evavic44** [comment]
Good idea

> This is a good idea, but more difficult to do 😂 - a lot of planning.
> 
> Maybe for the 2nd version. I was thinking to keep it simple for the first version. But we can try because a story is best 👍

This is a great idea. What is the status on this?

**Comment by eddiejaoude** [comment]
Thanks all for your support 👍 . Yes lets do this 💪 I think we need to have about 10 people though

**Comment by kaiwalyakoparkar** [comment]
I am ready! Let's discuss it

**Comment by muthuannamalai12** [comment]
I am also ready for it

**Comment by Evavic44** [comment]
> I am ready! Let's discuss it

Me too.

**Comment by kaiwalyakoparkar** [comment]
@eddiejaoude I think you will surely get 10+ in this discussion itself

**Comment by WebShivam** [comment]
yeah I'm ready too Let's do this

**Comment by adityaraute** [comment]
What's the status here? This happened already, right?

**Comment by eddiejaoude** [comment]
Oh yes this happened, thank you @adityaraute 👍 

For any news ideas, let's create new issues
