### ISSUE TITLE
Latest livestreams section on Home page

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/EddieHubCommunity.github.io#30]
Hi everyone 😃,
 
I was thinking it would be cool to have a section with the latest livestreams/videos, below or maybe above the Projects section.
This could give a newcomer an idea of the sort of community we are, by the titles of the videos and thumbnails. Or it could give awareness to something they didn't watch and was really cool like [this livestream](https://www.youtube.com/watch?v=sD5vCZfP210) about another organization open sourcing their projects.
 
Should we have a section for this on the home page? I'm not concerned about the complexity of this task in terms of technology and integration with the YouTube API for now. I was just wondering if this provides value to the community and the user going to our website.

What do you think? Let's start a discussion in the comments 😄. 

_Note: I was thinking how this is related to how Netflix shows like the latest content on their app  but this is a bit different 😅_

**Comment by eddiejaoude** [comment]
This is a great idea 👍 - we can keep it simple to begin with and make it more advanced as we go along. From the 2nd half of September (in a few weeks), I will have a more regular schedule too - so hopefully it will be clearer for everyone 🤓

**Comment by divyakumari12** [comment]
Yeah ,That would be a great help for newbies like me.

**Comment by Vyvy-vi** [comment]
Maybe we can use a GitHub action that keeps track of Eddie's YouTube rss feed, and embeds the link in the site?

**Comment by SaraJaoude** [comment]
We now have a new website, which also refers to the Newsletter and Blog and this will hopefully let any newcomers know more about what type of community this is.  

The schedule of live streams and calls is also going to be addressed in this issue: https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/174

If I missed anything can you raise a new issue please.
