### ISSUE TITLE
Favicon update

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/EddieHubCommunity.github.io#300]
### Description

update the Favicon https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/main/src/app/favicon.ico to use EddieHub's mascot

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍 

I think we can use the one from BioDrop

**Comment by rohan-kapse** [comment]
hey, @schmelto do u expect to update the biodrop repo favicon and replace it with auth folder favicon, right ?

**Comment by schmelto** [comment]
@eddiejaoude why use the facivon of biodrop I would go with a hubber maskot? Biodrop B doesn't seem right for the eddiehub community website in my opinion .

**Comment by eddiejaoude** [comment]
> @eddiejaoude why use the facivon of biodrop I would go with a hubber maskot? Biodrop B doesn't seem right for the eddiehub community website in my opinion .

sorry, yes you are correct, my favicon on BioDrop is still cached LOL with hubber - yes use the hubber mascot 👍

**Comment by schmelto** [comment]
> hey, @schmelto do u expect to update the biodrop repo favicon and replace it with auth folder favicon, right ?

@rohan-kapse update on the issue description. Hope now it is clear

**Comment by AniketNS** [comment]
Hey @eddiejaoude, Is this issue still open? Can I work on it?
