### ISSUE TITLE
[FEATURE] Move all h1, h2... to reusable react components

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#301]
### Description

Currently we have the same styles duplicated everywhere, moving these to components would be better

**Comment by Satoshi-Sh** [comment]
Hi Eddie, can I take this task?

**Comment by anhlee66** [comment]
Can you assign it for me, please.

**Comment by xkrishguptaa** [comment]
Hi @Satoshi-Sh @anhlee66 there are several things that can be converted into a react component; You can split this issue (create new issues)

For eg: An issue to componentize just the headers and work on this together

**Comment by Satoshi-Sh** [comment]
Thanks for the comment, xkrishguptaa. I will have a look at this and make some more new issues.
