### ISSUE TITLE
Jump to the top of the page instead of Linkedin Profile

### ISSUE THREAD

**Issue by Satoshi-Sh** [EddieHubCommunity/EddieHubCommunity.github.io#303]
## Problem
When I clicked on Cahllagerfeld's LinkedIn Icon in the moderator section, it brought me to the top of the page.
LinkedIn Url is set as "#" in the Moderator.jsx.

## Fix
Need to put his LinkedIn URL instead of "#"

or

If he doesn't want to share his LinkedIn Profile here
It's better not to render the icon.

### Screenshots

![Screenshot from 2023-11-04 16-51-48](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/73622805/a3b90f39-cf2c-49c8-a59e-3d340702364a)

**Comment by rohan-kapse** [comment]
hey, @Satoshi-Sh I agree, what can we do to fix it though?

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 

II fixed by checking for a url and then display the icon https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/commit/77227c1287d13c64b2a547ca29afde4b307c24ae
