### ISSUE TITLE
Some Images missing "alt" property 

### ISSUE THREAD

**Issue by Satoshi-Sh** [EddieHubCommunity/EddieHubCommunity.github.io#308]
## Bug
Some images are missing alt properties and have the following error message on the terminal when it's run locally. 

"Image is missing required "alt" property. Please add Alternative Text to describe the image for screen readers and search engines."

## Fix 
Make sure to give alt properties to all the images on the page and check if the message has gone away.

### Screenshots

![Screenshot from 2023-11-05 08-16-36](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/73622805/41db16a7-e0df-4f15-ad42-5acd87b93c98)
![Screenshot from 2023-11-05 08-18-02](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/73622805/86326c25-3663-4783-aea5-7750b4789d5b)

**Comment by abdqudus** [comment]
Can you assign this task to me?

**Comment by xkrishguptaa** [comment]
Please go ahead @abdqudus!
