### ISSUE TITLE
Remove Unnecessary Folder

### ISSUE THREAD

**Issue by Satoshi-Sh** [EddieHubCommunity/EddieHubCommunity.github.io#311]
### What would you like to share?

This application doesn't have auth pages, so the [auth] folder is not necessary.
## Folder Image
![Screenshot from 2023-11-06 18-06-33](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/73622805/81512557-65e2-4e98-bb75-18ec6511fed0)
Please delete the folder. 

### Additional information

You can check the discussion here about the auth page. https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/pull/307

![Screenshot from 2023-11-06 18-08-26](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/73622805/70e72c26-967e-4490-849f-48091c9f477e)

**Comment by xkrishguptaa** [comment]
Thank you for raising!

**Comment by jayantaadhikary** [comment]
Hey, I submitted a pull request for this issue. I am really sorry for not asking you to assign me to the issue before making a pull request.
