### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by ItsShibam** [EddieHubCommunity/EddieHubCommunity.github.io#312]
### Description

Icon overlapping in mobile view of the website.

### Screenshots

![issue](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/102949049/14bae1b5-ebc7-48be-b519-619405c6caab)

### Additional information

This is so visible issue I encountered on first visit to the website.

**Comment by ItsShibam** [comment]
Assign me to this issue @eddiejaoude

**Comment by xkrishguptaa** [comment]
Please go ahead @ItsShibam!

**Comment by ItsShibam** [comment]
Hi, @xkrishguptaa I submitted my PR a few days back.
Would you like to review

**Comment by xkrishguptaa** [comment]
I believe you pr has been merged, thank you for contributing #314
