### ISSUE TITLE
Gitpod link not working in README

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/EddieHubCommunity.github.io#336]
### Description

I clicked on the Develop with Gitpod link. It is not working.
I get the following error. This concern is also raised in #331 

### Screenshots

![image](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/43912470/1e0ec11a-88d1-4e67-ab15-b676be7e69ac)

**Comment by Bashamega** [comment]
Hello:)

I think this issue is already solved. Check this: 
![image](https://github.com/user-attachments/assets/38d0d187-25ed-4f83-9744-3380339ba012)

**Comment by adityaraute** [comment]
Yes, closing it now
