### ISSUE TITLE
Moderators has UI problems on Firefox

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/EddieHubCommunity.github.io#47]
## Actual
![imagem](https://user-images.githubusercontent.com/18630253/92030230-a6d66a80-ed5e-11ea-8b7b-0ff0cdad554b.png)

Screenshot taken on Mozilla Firefox browser.

## Expected
![imagem](https://user-images.githubusercontent.com/18630253/92030592-2ebc7480-ed5f-11ea-8b97-64b51bd1ce82.png)

Screenshot taken on Google Chrome browser.

_Note: This is just a reminder since our main target is Google Chrome. Still, we could investigate why this is happening and fix it 😃 ._

**Comment by Arvindjitta** [comment]
i guess its because of tailwind container, behaviour of it in firefox is little weird

**Comment by alrifay** [comment]
I tried the deployed site on Firefox, it looks very similar to Chrome's  except for the font, it slightly different.  
- Firefox: ![Firefox](https://user-images.githubusercontent.com/19517534/94974966-7b3ad180-0510-11eb-84cd-48d862f806e8.png)
- Chrome ![Chrome](https://user-images.githubusercontent.com/19517534/94975127-f0a6a200-0510-11eb-96f3-d0b77eb6ab4b.png)

**Comment by BOLT04** [comment]
@alrifay I think you are right 👍. When I changed the font-size of the description text to the same value on Chrome, it looks better:
![imagem](https://user-images.githubusercontent.com/18630253/94991913-3baace80-057e-11eb-8224-6f7692a0db14.png)


For the rest of the differences, it might be the size of my monitor 😅

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
