### ISSUE TITLE
welcome first time contributors

### ISSUE THREAD

**Issue by Arvindjitta** [EddieHubCommunity/EddieHubCommunity.github.io#50]
https://github.com/marketplace/actions/github-script#welcome-a-first-time-contributor

**Comment by VictoryWekwa** [comment]
Please what is to be done for this?

**Comment by BOLT04** [comment]
@Arvindjitta this is an awesome idea, thank you for raising this issue 😃!
@VictoryWekwa I believe @eddiejaoude would use that bot from the marketplace and setup the repo to use it. Then, with that Github action that gets triggered every PR, the contributor would get a message from the bot saying like "thanks for contributing. This is your first contribution, so welcome to the community 😃 "

**Example**
![imagem](https://user-images.githubusercontent.com/18630253/92158215-77d5fc80-ee23-11ea-859f-42bc418aa734.png)

This basically automates some of these common messages and hopefully gives a better experience to the contributors 👍

**Comment by VictoryWekwa** [comment]
oh! 
okay

**Comment by eddiejaoude** [comment]
@VictoryWekwa you could use the example they have in their docs. I think that would add value to the user already. What do you think @BOLT04 ?

Ideas:
- Maybe update the `body` field with a bit more information

I think creating the file `.github/workflows/first-timer.yml` in this repo would work (similar to this GitHub Action by @stemount https://github.com/EddieJaoudeCommunity/support/blob/main/.github/workflows/stale.yml)
```yaml
on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const creator = context.payload.sender.login
            const opts = github.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              if (issue.number === context.issue.number) {
                continue
              }

              if (issue.pull_request) {
                return // Creator is already a contributor.
              }
            }

            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Welcome, new contributor!'
            })
```

**Comment by BOLT04** [comment]
Yes I agree Eddie 👍

**Comment by VictoryWekwa** [comment]
Please can there be a break down of what exactly to be done for this?

**Comment by eddiejaoude** [comment]
@VictoryWekwa maybe this can be split into 2 issues:

1. get the GitHub Action triggering for the right events
2. customise the message 

I could try and do `1`, and you can then customisations it for point `2`

**Comment by eddiejaoude** [comment]
I am trying to abstract this Community Action so we can easily use it on multiple repos.

I have done this @VictoryWekwa https://github.com/EddieJaoudeCommunity/gh-action-community/blob/main/.github/workflows/community.yml

If you look at lines `14` and `15`, if you could improve the welcome messages that would be great. Let me know what you think 🤓

**Comment by VictoryWekwa** [comment]
Looks good already.
on line 14, how about having something like;
welcome: "#It's great having you contribute to this project. Feel free to raise an issue and create a Pull request. Welcome to the community!"

**Comment by eddiejaoude** [comment]
Sounds good, some thoughts:

- `#It's great` I think a space is needed after the `#`

> Feel free to raise an issue and create a Pull request. Welcome to the community

- this should go on the next line, I think this can be done with a `\n`

Also maybe add `if any questions please ask in Discord`

**Comment by VictoryWekwa** [comment]
okay. Great.
Will work on it and then create a PR.

**Comment by eddiejaoude** [comment]
Sounds good 👍 - don't worry about making it "perfect", I think this can be something we keep iterating on and make small improvements each time. 

Looking forward to seeing what you do 🤓 . Any questions let us know

**Comment by VictoryWekwa** [comment]
Okay. 
for **"# It's great**, 

>  I used the h1 tag instead of the # since i'm looking at it being a heading.


I just created a pull request [here](https://github.com/EddieJaoudeCommunity/gh-action-community/pull/24)
Am i to also create a pull request here?

**Comment by eddiejaoude** [comment]
Great 👍 , thanks @VictoryWekwa 

I am hoping a pull request on that repo is enough and I can use it on other repos by importing it via a GitHub Action, so I don't think another pull request here is needed.

Note: `#` is the same as `h1` (but single line markdown `h1` might be easier, so that is fine 👍 )

**Comment by eddiejaoude** [comment]
I think this issue is now solved? I will close it. Feel free to create a new issue if needed
