### ISSUE TITLE
Add AXE accessibility to Cypress

### ISSUE THREAD

**Issue by mikeysan** [EddieHubCommunity/EddieHubCommunity.github.io#67]
Eddie needs this done :) ps. assign it to him.

**Comment by eddiejaoude** [comment]
LOL anyone can do it I dont mind.

I think here is the npm dependency and it has config instructions https://www.npmjs.com/package/cypress-axe

**Comment by eddiejaoude** [comment]
New website is now live, I will close this issue, any suggestions can come in a new issue
