### ISSUE TITLE
Save the Cypress artifacts after Actions have run (failed)

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/EddieHubCommunity.github.io#69]
**Description**
>Cypress stores screenshots and videos when a test fails locally, we could keep these artifacts between builds. On GitHub Actions there is an official action for this "actions/upload-artifact" (check more info [here](https://github.com/cypress-io/github-action/issues/33)), which when used gives an additional dropdown on the Action page.

**More Links**
- https://docs.cypress.io/guides/guides/continuous-integration.html#Record-tests
- https://github.com/cypress-io/github-action#record-test-results-on-cypress-dashboard
- https://github.com/cypress-io/github-action#artifacts

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 👍

**Comment by eddiejaoude** [comment]
Thank you! New website is now live, I will close this issue, any suggestions can come in a new issue
