### ISSUE TITLE
Our community FAQs in README/Website

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#7]
Common questions/answers people ask when new to our community

- How do I join the Github Organisation
- ...

*Edit: In our `support` repo, we could have FAQs from the community questions*

**Comment by Kundan28** [comment]
How to create an organisation

**Comment by eddiejaoude** [comment]
@Kundan28 this is the FAQs for joining our community. In our `support` repo, we probably need to collate popular questions there

**Comment by Kundan28** [comment]
Thanks for the clarification.

**Comment by eddiejaoude** [comment]
No problem, always good to discuss these things and see other peoples opinions. Thank you 👍 - keep suggestions coming 🤓

**Comment by eddiejaoude** [comment]
FAQ now on new website
